config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: 'static_pages#contact', as: 'contact'

  get 'about', to: 'static_pages#about', as: 'about'

  get 'help', to: 'static_pages#help', as: 'help'

  root 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = nil)
    base="Weight Agent"
    if title
      content_for(:page_title) { base + ' | ' + title }
    else
      content_for?(:page_title) ? content_for(:page_title) : base
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    
    <%= render 'shared/meta' %>
    <%= render 'shared/favicons' %>

    <title>  <%= page_title %> </title>
    

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <%= render 'shared/shim' %>

    <!-- External Fonts -->
    <script src="//use.edgefonts.net/sirin-stencil.js"></script>
    <script src="//use.edgefonts.net/miama.js"></script>

  </head>
  <body>
  <div class="container">
 
      <%= render 'shared/navigation' %>

      <div class="jumbotron">
        <%= render 'shared/messages' %>
        <%= yield %>

        <br>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
      <!-- %= debug(params) if Rails.env.development? % -->
  </div>

  <%= render 'shared/footer' %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </body>
</html>

app/views/shared/_favicons.html.erb
<!-- https://www.iconfinder.com -->
<!-- https://www.iconfinder.com/icons/85827/scale_weight_icon#size=30 -->
<!-- Favicon tradicional -->
<%= favicon_link_tag 'weight-agent.png',     rel: 'shortcut icon' , type: 'image/png'%>
<!-- Favincon para Appel y Android -->
<%= favicon_link_tag 'weight-agent-60.png',  rel: 'apple-touch-icon', type: 'image/png' , size:'60x60' %>
<%= favicon_link_tag 'weight-agent-72.png',  rel: 'apple-touch-icon', type: 'image/png' , size:'72x72' %>
<%= favicon_link_tag 'weight-agent-120.png', rel: 'apple-touch-icon', type: 'image/png' , size:'120x120' %>
<%= favicon_link_tag 'weight-agent-152.png', rel: 'apple-touch-icon', type: 'image/png' , size:'152x152' %>
<%= favicon_link_tag 'weight-agent.png',     rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<hr>

<footer>
   <small>FM &copy; Company <%= Time.now.year %></small>
</footer>

app/views/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Weight Agent">
<meta name="author" content="Fernando J. Muñoz">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Weight Agent" %>">

app/views/shared/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Logo', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'shared/navigation_links' %>
      </ul>
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div>
  </div>
</div>

app/views/shared/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="active"><li><%= link_to 'Home', root_path %>  </li>
<li><%= link_to 'Contact', contact_path %></li>
<li><%= link_to 'About Us', about_path %></li>
<li><%= link_to 'Help', help_path %></li>

app/views/shared/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/static_pages/about.html.erb
<% page_title "About Us" %>

<h1>About Us</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% page_title "Contact" %>

<h1>Contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% page_title "Help" %>

<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Weight Agent</h1>